### ISSUE TITLE
[Android] 共通プロジェクト内で`Java.IO.IOException`がthrowされる

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#361]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#95 対応のためAndroidClientHandlerへ切り換えたと結果として、Androidでのネットワーク系の例外がそのまま`Java.IO.IOException`としてthrowされる状態になっている。

共通プロジェクトではJava.IO.IOExceptionがそもそも存在しないのでcatchできず、ステータスコードで表示を分岐できない。

COCOAの実行時に出力されるログには、次のように将来的なリリースで対応すると書いてある。

```
[monodroid] Not wrapping exception of type Java.IO.IOException from method `SendAsync`. This will change in a future release.
```

## 解決策についてお書きください / Describe the solution you'd like

最新のmonoandroidに更新する。`11.0`で対応したという情報がある。

https://github.com/xamarin/xamarin-android/pull/4601

monoandroidを更新してthrowされる例外を確認して、適切に対応する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

そもそもプラットフォーム固有のHTTPClientを使う必要があるか。
`System.Net.Http.HttpClient`で対応できるなら、`IHttpClientService`自体を廃止してしまった方が良い。

## その他 / Additional context

代替案を採用するにしても、monoandroidの更新はする。
また、このIssueではステータスコードによるエラー時の表示の分岐までは行わない。

**Comment by keiji** [comment]
MonoDroidのバージョンを11に設定しても状況は変わらず。
対応したと思っていたファイルがLegacy扱いになっていて、Issueは生き残りつつけている。

https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs

https://github.com/xamarin/xamarin-android/issues/3216

こちらで`HttpClient`をラップするクラスを作って、Android側で`Java.IO.*Exception`を適切に変換するしかなさそう。

**Comment by keiji** [comment]
自分で作ってるプロジェクト[Chino.Prism](https://github.com/keiji/chino.prism/tree/master/Chino.Prism)で試してみた結果。
MonoDroidもPrism等のライブラリも最新に近いものを使っているけれど、やはり上がってくるのは`Java.Net.UnknownHostException`

> [monodroid] Not wrapping exception of type Java.Net.UnknownHostException from method `SendAsync`. This will change in a future release.

```
Java.Net.UnknownHostException: Unable to resolve host "en.keiji.dev": No address associated with hostname ---> Java.Lang.RuntimeException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <1959115d56f8444789986cf39185638c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <1959115d56f8444789986cf39185638c>:0 
  at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect () [0x00000] in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Javax.Net.Ssl.HttpsURLConnection.cs:535 
  at Xamarin.Android.Net.AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 () [0x0007d] in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs:357 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
--- End of stack trace from previous location where exception was thrown ---

  at Xamarin.Android.Net.AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState) [0x000e4] in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs:406 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00286] in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs:287 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:506 
  at Chino.Prism.EnServer.GetDiagnosisKeysListAsync (Chino.Prism.ServerConfiguration serverConfiguration) [0x00069] in /Users/keiji_ariyama/Projects/Chino.Prism/Chino.Prism/EnServer.cs:52 
  at Chino.Prism.ViewModel.MainViewModel.DownloadDiagnosisKeysFromServer () [0x00055] in /Users/keiji_ariyama/Projects/Chino.Prism/Chino.Prism/ViewModel/MainViewModel.cs:217 
  --- End of managed Java.Net.UnknownHostException stack trace ---
java.net.UnknownHostException: Unable to resolve host "en.keiji.dev": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 15 more
```

**Comment by b-wind** [comment]
AndroidMessageHandler.cs で対応しているように見えますね。（リリースされているコードかどうかはよくわからないです）

https://github.com/xamarin/xamarin-android/blob/1e5bfa3ff0ae18ce9407677667f05a9bfba53478/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L303-L320

**Comment by b-wind** [comment]
実装を切り替えている部分はあるようですが、どう言う条件なのかはよく分かってないです。

https://github.com/xamarin/xamarin-android/blob/1e5bfa3ff0ae18ce9407677667f05a9bfba53478/src/Mono.Android/Mono.Android.csproj#L351-L352

https://github.com/xamarin/xamarin-android/blob/1e5bfa3ff0ae18ce9407677667f05a9bfba53478/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L12-L13

**Comment by b-wind** [comment]
対応リリースが出てないようならワークアラウンドとしてはこちらの物が無難そうに見えます。

https://github.com/xamarin/xamarin-android/issues/2651#issuecomment-544228575

**Comment by keiji** [comment]
> 対応リリースが出てないようならワークアラウンドとしてはこちらの物が無難そうに見えます。
> https://github.com/xamarin/xamarin-android/issues/2651#issuecomment-544228575

そうですね。
Issueの中で「ぜんぶ`WebException`に入れちゃうのはおかしくない？」みたいな指摘が出ていたので、例外のマッピングがまとまっていないのかなと思います。

ワークアラウンドにしてもざっくり見た限り、ぼくがやりたいのは`UnknownHostException`と`IOException`を分けて出すようにするくらいですね。その二つは`IOException`でまとめられるので、実質`Exception`だけ取る今の実装でも足りるかなと言う感じになっています（とても気持ち悪く感じますが）。

提案いただいていた #94 に対応するのはステータスコード見ればいいので、例外とステータスコードによる分岐は分けて考えることにします。

**Comment by b-wind** [comment]
ここに記しておくのが良いのかな。

将来的に AndroidClientHandler は非推奨に。代わりに AndroidMessageHandler が用意される。

https://github.com/xamarin/xamarin-android/pull/6541

**Comment by b-wind** [comment]
WebException への変換と例外種類の判別は Xamarin.Android v10.4 で取り込まれた模様。
これ以降 v11.x 系でもほぼ変更は無し。


https://github.com/xamarin/xamarin-android/commit/83521e4e0bacaae3f2c0cc6a5d561f418a03e575


v12 からは従来の AndroidClientHandler が AndroidClientHandler.Legacy.cs に移されて、AndroidMessageHandler が推奨（っぽい）ですね。

https://github.com/xamarin/xamarin-android/pull/6541
