### ISSUE TITLE
マイグレーションのユニットテストを拡充する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#524]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#520 に関連した課題。

マイグレーション処理のユニットテストは[MigrationServiceTests](https://github.com/cocoa-mhlw/cocoa/blob/develop/Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Migration/MigrationServiceTests.cs)にまとまっているが、 #517 の不具合を発見できなかった。

## 解決策についてお書きください / Describe the solution you'd like

#517 のケースを発見できるユニットテストを追加する。

1. release_1_4_0ブランチをベースに規約への合意時刻に`DateTime.MinValue`が保存されているケースを追加して、例外（ `ArgumentOutOfRangeException` ）が起こることを確認
2. Hot-fix（ #518 ）を適用して、ユニットテストが正常に完了する（例外が発生しない）ことを確認
3. developブランチへPull Requestを提出

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

特になし。

## その他 / Additional context

`MigrationServiceTests`が長くなっていて見通しが悪いので、始点のバージョンからファイルを分けることを検討してもいいかもしれない（`MigrationService_From1_0_0_Tests`, `MigrationService_From1_2_2_Tests`のような形で）。

**Comment by keiji** [comment]
Done.

追加したテストを実行した結果、正しく失敗を検出できることを確認した。
https://github.com/cocoa-mhlw/cocoa/runs/4344513219?check_suite_focus=true

```
[xUnit.net 00:00:10.96]     Covid19Radar.UnitTests.Services.Migration.MigrationServiceTests.Migrate_100to130Async [FAIL]
  Failed Covid19Radar.UnitTests.Services.Migration.MigrationServiceTests.Migrate_100to130Async [1 s]
  Error Message:
   System.ArgumentOutOfRangeException : The added or subtracted value results in an un-representable DateTime. (Parameter 't')
  Stack Trace:
     at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at Covid19Radar.Services.Migration.Migrator_1_3_0.MigrateDateTimeToEpoch(String dateTimeKey, String epochKey, TimeSpan differential) in /home/runner/work/cocoa/cocoa/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs:line 67
   at Covid19Radar.Services.Migration.Migrator_1_3_0.ExecuteAsync() in /home/runner/work/cocoa/cocoa/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs:line 41
   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync(Version fromVersion) in /home/runner/work/cocoa/cocoa/Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs:line 221
   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync() in /home/runner/work/cocoa/cocoa/Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs:line 136
   at Covid19Radar.UnitTests.Services.Migration.MigrationServiceTests.Migrate_100to130Async() in /home/runner/work/cocoa/cocoa/Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Migration/MigrationServiceTests.cs:line 884
--- End of stack trace from previous location where exception was thrown ---

Failed!  - Failed:     1, Passed:   246, Skipped:     0, Total:   247, Duration: 13 s - /home/runner/work/cocoa/cocoa/Covid19Radar/Tests/Covid19Radar.UnitTests/bin/Debug/netcoreapp3.1/Covid19Radar.UnitTests.dll (netcoreapp3.1)
```
