### ISSUE TITLE
同じ日付のDailySummaryが複数件有ると強制終了する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#732]
## 不具合の内容 / Describe the bug

接触確認を繰り返したときに、同じ日付で（データが異なる）DailySummaryが得られることがある。
現状の処理はDaySummaryの日付は１件しかない前提で`ToDict`でまとめているので例外（ArgumentException: An item with the same key has already been added. Key）が発生して強制終了する。

後から来た診断キーで接触が確認されたデータと思われる。

```
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/04 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 164742","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 144450","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/01-16 01:23:33.403 V/mono-stdout(29527): "2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/05 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/08 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 250500","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/09 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 425400","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/10 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/11 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 192240","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/01-16 01:23:33.407 V/mono-stdout(29527): "2022/01/16 01:23:33","Debug","ScoreSum: 148272","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/12 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug",ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/13 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 92370","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/14 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 177000","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","GetDateTime: 2022/01/14 0:00:00","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","171","Android","12","Pixel 3","Physical","APP_VERSION","5"
"2022/01/16 01:23:33","Debug","ScoreSum: 750","OnClickExposures","/Users/keiji_ariyama/Projects/cocoa/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs","172","Android","12","Pixel 3","Physical","APP_VERSION","5"
[AndroidRuntime] Shutting down VM
[AndroidRuntime]   at Android.App.SyncContext+<>c01-16 01:23:33.428 E/AndroidRuntime(29527): FATAL EXCEPTION: main
[AndroidRuntime] Process: jp.go.mhlw.covid19radar, PID: 29527
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.ArgumentException: An item with the same key has already been added. Key: 01/14/2022 00:00:00
[AndroidRuntime]   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000dd] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[AndroidRuntime]   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[AndroidRuntime]   at System.Linq.Enumerable.ToDictionary[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x00058] in <367ee00826fa48f690092f258879ad20>:0 
[AndroidRuntime]   at System.Linq.Enumerable.ToDictionary[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <367ee00826fa48f690092f258879ad20>:0 
[AndroidRuntime]   at Covid19Radar.ViewModels.HomePageViewModel.<get_OnClickExposures>b__38_0 () [0x0024c] in <be9e323095dc4fd8abe5a7d967df6716>:0 
[AndroidRuntime]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[AndroidRuntime]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e4d148f1f9084704abe34fd71080bb04>:0 
[AndroidRuntime]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e4d148f1f9084704abe34fd71080bb04>:0 
[AndroidRuntime]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e4d148f1f9084704abe34fd71080bb04>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.82(intptr,intptr)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7842)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] 	at01-16 01:23:33.434 I/MonoDroid(29527): Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
[MonoDroid]   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
[MonoDroid] android.runtime.JavaProxyThrowable: System.ArgumentException: An item with the same key has already been added. Key: 01/14/2022 00:00:00
[MonoDroid]   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000dd] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[MonoDroid]   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[MonoDroid]   at System.Linq.Enumerable.ToDictionary[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x00058] in <367ee00826fa48f690092f258879ad20>:0 
[MonoDroid]   at System.Linq.Enumerable.ToDictionary[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <367ee00826fa48f690092f258879ad20>:0 
[MonoDroid]   at Covid19Radar.ViewModels.HomePageViewModel.<get_OnClickExposures>b__38_0 () [0x0024c] in <be9e323095dc4fd8abe5a7d967df6716>:0 
[MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <ded7257c25e040a9b40b0d7edd70e9b0>:0 
[MonoDroid]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e4d148f1f9084704abe34fd71080bb04>:0 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e4d148f1f9084704abe34fd71080bb04>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e4d148f1f9084704abe34fd71080bb04>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.82(intptr,intptr)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:938)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[MonoDroid] 	at android.os.Looper.loopOnce(Looper.java:201)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:288)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7842)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

`01/14/2022 00:00:00`のキーが2つある。
それぞれScoreSumが違うので重複ではない。片方は `177000` と大きな値で、もう片方が `750` なので、新しい診断キーで接触確認をした（同じ日付に追加の接触が検出された）挙動と考える。

## 再現手順 / Steps to reproduce

再現すごく面倒だけど、要するにDailySummaryから同一日付のデータを２件以上返せば再現する。モックでやると良いかも。

## 期待される挙動 / Expected behavior

強制終了しない。

~~同一日付のDailySummaryが複数兼有った場合、それぞれのデータを加算（マージ）して処理する。
で、いい~~ と思うんですが、どうでしょう？ > @daisuke-nogami 

いや、合算しちゃダメか。

## 動作環境 / Environments

- デバイス：（例：Pixel 5、iPhone 6 等）
- OS：（例：Android、iOS）
- バージョン：(例：1.2.2)

**Comment by keiji** [comment]
同じ日付のDailySummary（に紐付くExposureWindow）が複数ある場合は、それぞれについてリスク値を評価する。

これが一番シンプルでよさそう。 > @daisuke-nogami

**Comment by keiji** [comment]
ExposureWindowはDailySummaryに紐付いているのではなくて、純粋に日付別に取得することになるので、同じ日付のDailySummaryが複数兼有ったときに、ExposureWindowがどのDailySummaryに紐付くかという判断が難しい構造。うーん。やっぱり合算かなぁ

**Comment by keiji** [comment]
ちょっと整理。

あとで追加された同じ日付の診断キーで接触が上がると言うことは、既存の接触とは違う陽性者と言うこと、そのDailySummaryは合算せず、個別に見るべき。

**Comment by keiji** [comment]
これ見るとExposureWindowを元にDailySummaryを計算している。

https://developers.google.com/android/exposure-notifications/meaningful-exposures#daily-summaries

一日の接触を合算して、閾値を超えるか、超えないかという話と理解した。
その視点で見ると、接触が確認されたときにEqualsで比較して一致しなければ同じ日付でも異なるデータとして取り扱ってる今の保存処理の時点でおかしいことになる。

保存の時に、すでに保存済みの日付のDailySummaryがあれば、そのデータと合算して、閾値を超えれば通知で知らせる。
内部データ上で日付は常に一つだけ（単純にリストを追加をしない）という動きをするのがよさそう。

この挙動がもっとも合理的か（本当に合理的かは寝てから考える）。

**Comment by keiji** [comment]
一度データ全部消してから同じ診断キーで接触確認やり直したら、同じ日付のDailySummaryは合算で得られたので、想定した取り扱いで間違いはなさそう。岩手に3m

**Comment by daisuke-nogami** [comment]
> これ見るとExposureWindowを元にDailySummaryを計算している。
> https://developers.google.com/android/exposure-notifications/meaningful-exposures#daily-summaries
> 一日の接触を合算して、閾値を超えるか、超えないかという話と理解した。

はい、その通りで、ExposureWindowを使って計算すれば正しいDailySummaryを出せます（以前、実機のログで確認済み）。
なので極論するとDailySummaryをすっ飛ばして自力計算してもよい、とはなっちゃうんですよね…

> 保存の時に、すでに保存済みの日付のDailySummaryがあれば、そのデータと合算して、閾値を超えれば通知で知らせる。

合算ではなく最大値を取る方がただしいかと思います。あるいはDailySummaryは都度入れ替え、とか。
（DailySummaryは、毎回、端末の中に残っているExposure Windowを全部見て計算し直しているはずなので、
　合算では初回に拾ってしまったものが重複カウントされるはず）

**Comment by keiji** [comment]
最大値！　それですね！
DailySummary入れ替えだと、今回のようにいきなり750とかに下がったときに接触事実が消えてしまうことになるので良くないかなと思います。

今のところ #734 では合算で進めているので、このPull Requestを変更して最大値を取るようにします。

**Comment by kvaluation** [comment]
> あるいはDailySummaryは都度入れ替え

getDailySummaries()は、本来、既存の対象となる全てのExposureWindowを対象に計算をするのかと思いますので、最新の計算結果が常にその時点で正しいのかなと考えておりました。
https://developers.google.com/android/exposure-notifications/exposure-notifications-api#getdailysummaries

> 750とかに下がった
どちらかというと、これが不思議な気がします。

1回目のgetDailySummaries()では、14日前（かな）の対象とするExposureWindowが10個あったけれど、
2回目のgetDailySummaries()では、多くが15日前となって2回目実行時点では10個中8個が対象外となってスコアが750とかに下がるのは、自然ですよね。

そうでない日時の関係で、2回目で750に下がるのは、仕様として正しい動作結果ではないように感じました。

同一の接触日についての複数の陽性者の登録、登録日が違うと、追い掛けでスコアが変わるとのことですので、DailySummaryを計算するごとにExposureWindowが削除されているわけではないだろうと思います。
https://github.com/cocoa-mhlw/cocoa/issues/605#issuecomment-1008575244

ヤヤコシイ話なので色々私の方で誤解があるかもですが。

**Comment by keiji** [comment]
今回の場合なんですが、問題の日は1/14で、1期限切れになるような日付ではないんですよね。SymptomDateを考慮しても、やっぱりExposureWindow含めて有効であるべき期間です。

また、一度COCOAのストレージを全消去した後、まったく同じキーで接触確認を実行（Android版はこれで同一キーに接触確認をしないというENの制約をリセットできる）したところ、結果は古い方が表示されて、あとから来た750の方は跡形もなく消えてしまいました。

今回のケース、後勝ちにして750に寄るというのは個人的には避けたいところです。利用者からしてみれば特に理由もなくスコアが突然下がるわけなので。

 * 接触があったと判定されたら、14日間は「その日は接触の可能性があるよ」と表示され続ける。
 * 仮に低リスクの日が、あとから追加された診断キーで接触確認をしたところ、接触の可能性があったと判定されれば、その旨通知する。

と言うのが、利用者が期待する挙動と考えます。

**Comment by daisuke-nogami** [comment]
おお、これエラーの中身をみてなかったのですが、あとから返るDailySumの数字が少なかったのですね。
バグにしか見えない挙動だ…

期限切れになるような日付の接触だったとしても、（潜伏期間も感染可能期間も過ぎたタイミングになりつつあるとは言え）リスクのある接触がなくなるわけではないので、通知をするのが正しい挙動でしょう。
という点で「最大値を取る」で正しい挙動だと思います。
